/* eslint-disable no-console */
// Aggressive unavatar.io fallback for profiled people who still lack a
// photo after the Wikipedia, homepage, and twitter chains. Tries multiple
// platforms (X, GitHub, Substack, Telegram) with long delays so unavatar
// doesn't rate-limit us. Idempotent.

import { mkdir, writeFile, stat } from "node:fs/promises";
import path from "node:path";

import { people } from "../src/lib/people";
import { photoIndex as existingIndex } from "../src/data/photo-index";

const PUBLIC_DIR = path.resolve(import.meta.dir, "..", "public", "people");
const MANIFEST_PATH = path.resolve(import.meta.dir, "..", "src", "data", "photo-index.ts");
const USER_AGENT = "Mozilla/5.0 strategy-atlas-photo/0.1";

async function fileExists(p: string): Promise<boolean> {
  try {
    const s = await stat(p);
    return s.isFile() && s.size > 0;
  } catch {
    return false;
  }
}

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

// Returns true on success (image >= 5KB written to dest).
async function tryUnavatar(
  platform: string,
  handle: string,
  dest: string,
): Promise<boolean> {
  const url = `https://unavatar.io/${platform}/${encodeURIComponent(handle)}?fallback=false`;
  try {
    const res = await fetch(url, {
      headers: { "User-Agent": USER_AGENT },
      redirect: "follow",
      signal: AbortSignal.timeout(15000),
    });
    if (res.status === 429) return false;
    if (!res.ok) return false;
    const buf = new Uint8Array(await res.arrayBuffer());
    if (buf.byteLength < 5_000) return false; // skip placeholder pixel
    await writeFile(dest, buf);
    return true;
  } catch {
    return false;
  }
}

// Best-guess GitHub handle from a person's id and twitter, if any.
function candidateHandles(p: {
  id: string;
  twitter?: string;
  homepage?: string;
}): string[] {
  const out = new Set<string>();
  if (p.twitter) out.add(p.twitter.replace(/^@/, "").trim());
  // Common ID-derived handle: collapse hyphens, drop final initials
  out.add(p.id.replace(/-/g, ""));
  out.add(p.id.replace(/-/g, "_"));
  // Homepage subdomain (often github username for academics)
  if (p.homepage) {
    try {
      const u = new URL(p.homepage);
      const sub = u.hostname.split(".")[0];
      if (sub && sub.length > 2 && sub !== "www") out.add(sub);
    } catch {
      // ignore
    }
  }
  return Array.from(out).filter((h) => h && h.length > 1);
}

async function main() {
  await mkdir(PUBLIC_DIR, { recursive: true });

  const finalIndex: Record<string, string> = { ...existingIndex };
  // Pick up files already on disk under any extension.
  for (const p of people) {
    if (finalIndex[p.id]) continue;
    for (const ext of [".jpg", ".png", ".webp"]) {
      if (await fileExists(path.join(PUBLIC_DIR, `${p.id}${ext}`))) {
        finalIndex[p.id] = `/people/${p.id}${ext}`;
        break;
      }
    }
  }

  // Target: profiled people still missing a photo. Anyone the board renders.
  const candidates = people.filter((p) => p.profile && !finalIndex[p.id]);
  console.log(
    `[unavatar-aggressive] missing profiled photos: ${candidates.length}`,
  );

  const platforms = ["x", "github", "substack", "telegram"];
  let downloaded = 0;
  const errors: { id: string; reason: string }[] = [];

  for (let i = 0; i < candidates.length; i++) {
    const p = candidates[i];
    const handles = candidateHandles(p);
    let ok = false;
    for (const platform of platforms) {
      if (ok) break;
      for (const h of handles) {
        const dest = path.join(PUBLIC_DIR, `${p.id}.jpg`);
        const success = await tryUnavatar(platform, h, dest);
        // Long delay to avoid 429 from unavatar
        await sleep(2500);
        if (success) {
          finalIndex[p.id] = `/people/${p.id}.jpg`;
          downloaded++;
          console.log(
            `[unavatar-aggressive] ${downloaded} ok: ${p.id} via ${platform}/${h}`,
          );
          ok = true;
          break;
        }
      }
    }
    if (!ok) errors.push({ id: p.id, reason: "no-platform-match" });
  }

  console.log(
    `[unavatar-aggressive] done. downloaded ${downloaded}, missing ${errors.length}`,
  );

  // Rewrite manifest.
  const orderedIds = Object.keys(finalIndex).sort();
  const manifest =
    "// Auto-generated by scripts/fetch-wikipedia-photos.ts. Do not edit by hand.\n" +
    "// Run `bun run scripts/fetch-wikipedia-photos.ts` to refresh.\n\n" +
    "export const photoIndex: Record<string, string> = {\n" +
    orderedIds
      .map((id) => `  ${JSON.stringify(id)}: ${JSON.stringify(finalIndex[id])},`)
      .join("\n") +
    "\n};\n";
  await writeFile(MANIFEST_PATH, manifest, "utf8");

  if (errors.length) {
    console.log("[unavatar-aggressive] still missing:");
    for (const e of errors) console.log(`  - ${e.id}`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
