/* eslint-disable no-console */
// Fetch person photos via unavatar.io for profiled people who still lack a
// photo after the Wikipedia/Wikidata/Commons chain in fetch-wikipedia-photos.ts
// has run. unavatar.io aggregates X/Twitter, GitHub, Gravatar, and a few
// others; for newer AI safety researchers without Wikipedia articles, the
// Twitter handle in their profile is usually the only public photo source.
//
// Run with: bun run scripts/fetch-twitter-photos.ts
// Idempotent: skips anyone who already has a photo on disk or in the manifest.

import { mkdir, writeFile, stat } from "node:fs/promises";
import path from "node:path";

import { people } from "../src/lib/people";
import { photoIndex as existingIndex } from "../src/data/photo-index";

const PUBLIC_DIR = path.resolve(import.meta.dir, "..", "public", "people");
const MANIFEST_PATH = path.resolve(import.meta.dir, "..", "src", "data", "photo-index.ts");
const USER_AGENT =
  "strategy-atlas/0.1 (https://github.com/noahlloydrobson/strategy-atlas; AI safety atlas)";

async function fileExists(p: string): Promise<boolean> {
  try {
    const s = await stat(p);
    return s.isFile() && s.size > 0;
  } catch {
    return false;
  }
}

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

async function fetchAvatar(handle: string, dest: string): Promise<boolean> {
  // Try X first (more current), then GitHub if it looks like a dev handle.
  const url = `https://unavatar.io/x/${encodeURIComponent(handle)}?fallback=false`;
  const res = await fetch(url, {
    headers: { "User-Agent": USER_AGENT },
    redirect: "follow",
  });
  if (!res.ok) return false;
  const buf = new Uint8Array(await res.arrayBuffer());
  // unavatar returns a tiny placeholder when fallback is disabled and the
  // handle has no avatar. Treat anything under ~1KB as missing.
  if (buf.byteLength < 1024) return false;
  await writeFile(dest, buf);
  return true;
}

async function main() {
  await mkdir(PUBLIC_DIR, { recursive: true });

  const profiled = people.filter((p) => p.profile);
  const candidates = profiled.filter(
    (p) => !p.photoUrl && !existingIndex[p.id] && p.twitter,
  );
  console.log(
    `[twitter-photos] profiled=${profiled.length}, missing-with-twitter=${candidates.length}`,
  );

  const finalIndex: Record<string, string> = { ...existingIndex };
  let downloaded = 0;
  const errors: { id: string; reason: string }[] = [];

  for (let i = 0; i < candidates.length; i++) {
    const p = candidates[i];
    const handle = (p.twitter ?? "").replace(/^@/, "").trim();
    if (!handle) continue;
    const dest = path.join(PUBLIC_DIR, `${p.id}.jpg`);
    if (await fileExists(dest)) {
      finalIndex[p.id] = `/people/${p.id}.jpg`;
      continue;
    }
    try {
      const ok = await fetchAvatar(handle, dest);
      if (ok) {
        finalIndex[p.id] = `/people/${p.id}.jpg`;
        downloaded++;
        if (downloaded % 5 === 0) {
          console.log(
            `[twitter-photos] downloaded ${downloaded}/${candidates.length} (latest: ${p.id})`,
          );
        }
      } else {
        errors.push({ id: p.id, reason: "no-avatar-or-too-small" });
      }
    } catch (e) {
      errors.push({ id: p.id, reason: (e as Error).message });
    }
    await sleep(300); // be polite to unavatar
  }

  console.log(
    `[twitter-photos] downloaded ${downloaded}, failed ${errors.length}`,
  );

  // Rewrite manifest with new entries.
  const orderedIds = Object.keys(finalIndex).sort();
  const manifest =
    "// Auto-generated by scripts/fetch-wikipedia-photos.ts. Do not edit by hand.\n" +
    "// Run `bun run scripts/fetch-wikipedia-photos.ts` to refresh.\n\n" +
    "export const photoIndex: Record<string, string> = {\n" +
    orderedIds
      .map((id) => `  ${JSON.stringify(id)}: ${JSON.stringify(finalIndex[id])},`)
      .join("\n") +
    "\n};\n";
  await writeFile(MANIFEST_PATH, manifest, "utf8");

  if (errors.length) {
    console.log("[twitter-photos] sample failures:");
    for (const e of errors.slice(0, 20)) console.log(`  - ${e.id}: ${e.reason}`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
